{% set version = '5.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rferns
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rFerns_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rFerns/rFerns_{{ version }}.tar.gz
  sha256: 78da671e18dc1fb499eddcc6db7eedd69cef673ba0b46c873bd95615cbb583fb

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('c') }}                # [not win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - llvm-openmp                  # [osx]
    - r-base
  run:
    - libgomp                      # [win]
    - llvm-openmp                  # [osx]
    - r-base

test:
  commands:
    - $R -e "library('rFerns')"           # [not win]
    - "\"%R%\" -e \"library('rFerns')\""  # [win]

about:
  home: https://gitlab.com/mbq/rFerns
  license: GPL-2.0-or-later
  summary: Provides the random ferns classifier by Ozuysal, Calonder, Lepetit and Fua (2009)
    <doi:10.1109/TPAMI.2009.23>, modified for generic and multi-label classification
    and featuring OOB error approximation and importance measure as introduced in Kursa
    (2014) <doi:10.18637/jss.v061.i10>.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rFerns
# Type: Package
# Title: Random Ferns Classifier
# Version: 5.0.0
# Authors@R: person( c("Miron","Bartosz"),"Kursa", role=c("aut","cre"), email="M.Kursa@icm.edu.pl", comment=c(ORCID="0000-0001-7672-648X") )
# Description: Provides the random ferns classifier by Ozuysal, Calonder, Lepetit and Fua (2009) <doi:10.1109/TPAMI.2009.23>, modified for generic and multi-label classification and featuring OOB error approximation and importance measure as introduced in Kursa (2014) <doi:10.18637/jss.v061.i10>.
# Encoding: UTF-8
# URL: https://gitlab.com/mbq/rFerns
# BugReports: https://gitlab.com/mbq/rFerns/-/issues
# License: GPL (>= 2)
# Suggests: testthat
# RoxygenNote: 7.1.1
# NeedsCompilation: yes
# Packaged: 2021-09-21 12:11:46 UTC; mbq
# Author: Miron Bartosz Kursa [aut, cre] (<https://orcid.org/0000-0001-7672-648X>)
# Maintainer: Miron Bartosz Kursa <M.Kursa@icm.edu.pl>
# Repository: CRAN
# Date/Publication: 2021-09-22 10:00:13 UTC
